version: '3.7'

services:

  backend:
    build:
      context: .
    environment:
      GA_ID: undefined
      JCO_DATABASE_URI: postgres://app:mysecretpassword@postgres/app
      # RAVEN_DSN: to-be-configured
    image: jibrelnetwork/tokensale-backend:latest
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    volumes:
      - backend-media:/app/media

  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mysecretpassword
    image: postgres:9-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  backend-media:
  postgres-data:
