version: '3.2'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  jco: &jco_service_definition
    build:
      context: .
    command: app
    environment: &jco_environment_definition
      - DB_HOST=postgres
      - DB_USER=jco
      - DB_PASSWORD=mysecretpassword
      - JCO_DATABASE_URI=postgres://jco:mysecretpassword@postgres/jco
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbit:5672//
      - SECRET_KEY=GENERATE-YOUR-UNIQUE-SECRET-KEY-64-CHARS-LONG
      - RAVEN_PROJECT_ID=600330
      - RAVEN_SECRET=bc12312bcb2312b3c12c3b12da8a9cc9:d6bfc155c6bc312cbc412bcb623cb6c3
      - DJANGO_SETTINGS_MODULE=jco.settings
      - RECAPTCHA_ENABLED=

    image: jibrelnetwork/jco-backend:latest
    ports:
      - 8000:80
    restart: on-failure
    volumes:
      - jco-uploads:/app/uploads

  jco-beat:
    <<: *jco_service_definition
    depends_on:
      - rabbit
    command: celerybeat
    ports: []

  jco-worker:
    <<: *jco_service_definition
    depends_on:
      - rabbit
    command: celeryworker
    ports: []

  postgres:
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=jco
      - POSTGRES_USER=jco
      - POSTGRES_PASSWORD=mysecretpassword
    image: postgres:9
    ports:
      - 5432:5433
    volumes:
      - jco-postgres-data:/var/lib/postgresql/data

volumes:
  jco-uploads:
  jco-postgres-data:
