# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 09:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import jco.api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('fullname', models.CharField(blank=True, max_length=120)),
                ('citizenship', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residency', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('town', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=120)),
                ('terms_confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('is_identity_verified', models.BooleanField(default=False, verbose_name='Approved')),
                ('is_identity_verification_declined', models.BooleanField(default=False, verbose_name='Declined')),
                ('document_url', models.URLField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('is_document_skipped', models.BooleanField(default=False)),
                ('onfido_applicant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('onfido_document_id', models.CharField(blank=True, max_length=200, null=True)),
                ('onfido_check_id', models.CharField(blank=True, max_length=200, null=True)),
                ('onfido_check_status', models.CharField(blank=True, max_length=200, null=True)),
                ('onfido_check_result', models.CharField(blank=True, max_length=200, null=True)),
                ('onfido_check_created', models.DateTimeField(blank=True, null=True)),
                ('verification_started_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('withdraw_address', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_presale_account', models.BooleanField(default=False)),
                ('is_sale_allocation', models.BooleanField(default=True)),
                ('tracking', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('is_usable', models.BooleanField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sended', models.DateTimeField(null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'affiliate',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=jco.api.models.unique_document_filename, verbose_name='uploaded document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sended', models.DateTimeField(null=True)),
                ('is_sended', models.BooleanField(default=False)),
                ('rendered_message', models.TextField(blank=True, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40)),
                ('operation', models.CharField(choices=[('change_address', 'Change Withdraw Address'), ('withdraw_token', 'Withdraw TOKEN ')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('last_notification_sent_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='PresaleToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.FloatField()),
                ('currency_to_usd_rate', models.FloatField(default=0)),
                ('usd_value', models.FloatField(default=0)),
                ('created', models.DateTimeField()),
                ('comment', models.CharField(default='ANGEL ROUND / PRESALE', max_length=32)),
                ('is_sale_allocation', models.BooleanField()),
                ('is_presale_round', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presale_token',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_currency', models.CharField(max_length=10)),
                ('variable_currency', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_to_usd_rate', models.FloatField()),
                ('usd_value', models.FloatField()),
                ('token_to_usd_rate', models.FloatField(help_text='If you change this value and save - token_value will be recalculated as token_value = usd_value / token_to_usd_rate')),
                ('token_value', models.FloatField()),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('is_sale_allocation', models.BooleanField(default=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'db_table': 'TOKEN',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('value', models.FloatField()),
                ('mined', models.DateTimeField()),
                ('block_height', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='UserTokenPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_token_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_token_price',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('to', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField()),
                ('mined', models.DateTimeField(blank=True, null=True)),
                ('block_height', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='not_confirmed', max_length=20)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='withdraws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdraw',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='token', to='api.Transaction'),
        ),
    ]
