# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('fullname', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120, unique=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('citizenship', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residency', models.CharField(blank=True, max_length=120)),
                ('terms_confirmed', models.BooleanField(default=False)),
                ('docs_received', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('is_usable', models.BooleanField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Jnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=64, unique=True)),
                ('currency_to_usd_rate', models.FloatField()),
                ('usd_value', models.FloatField()),
                ('jnt_to_usd_rate', models.FloatField()),
                ('jnt_value', models.FloatField()),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'db_table': 'JNT',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_currency', models.CharField(max_length=10)),
                ('variable_currency', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('value', models.FloatField()),
                ('mined', models.DateTimeField()),
                ('block_height', models.IntegerField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='jnt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Transaction', unique=True),
        ),
    ]
