# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='onfido_applicant_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='onfido_check_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
