# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 11:51
from __future__ import unicode_literals

from django.db import migrations


def add_ico_states(apps, schema_editor):
    ICOState = apps.get_model('api', 'ICOState')
    ICOState.objects.create(id='NOT_STARTED', order=0)
    ICOState.objects.create(id='SALE_STARTED', order=1)
    ICOState.objects.create(id='SALE_FINISHED', order=2)
    ICOState.objects.create(id='ICO_FINISHED', order=3)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_icostate'),
    ]

    operations = [
        migrations.RunPython(add_ico_states)
    ]
