# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 11:51
from __future__ import unicode_literals

from django.db import migrations


def add_ico_states(apps, schema_editor):
    ICOState = apps.get_model('api', 'ICOState')
    from jco.api.models import ICO_STATES

    for i, state in enumerate(ICO_STATES):
        ICOState.objects.create(id=state, order=i)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_icostate'),
    ]

    operations = [
        migrations.RunPython(add_ico_states)
    ]
