# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='town',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
