# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171115_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='onfido_check_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='onfido_check_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='onfido_check_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='onfido_document_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
