# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171116_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='onfido_applicant_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='onfido_check_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='onfido_document_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
