# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171116_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('to', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField()),
                ('mined', models.DateTimeField()),
                ('block_height', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address')),
            ],
            options={
                'db_table': 'withdraw',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
