# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171122_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='etherium_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
