# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_etherium_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jnt',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jnt', to='api.Transaction'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='block_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='mined',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(max_length=120),
        ),
    ]
