# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20171123_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='etherium_address',
            new_name='withdraw_address',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='withdraws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address'),
        ),
    ]
