# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171123_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address'),
        ),
    ]
