# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_account_tracking'),
        ('api', '0010_auto_20171123_2220'),
    ]

    operations = [
    ]
