# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
        ('api', '0012_merge_20171124_0958'),
    ]

    operations = [
    ]
