# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20171124_1224'),
        ('api', '0014_auto_20171124_1240'),
    ]

    operations = [
    ]
