# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20171124_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_identity_verification_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
