# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171125_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='document_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sended',
            field=models.BooleanField(default=False),
        ),
    ]
