# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171125_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_identity_verification_declined',
            field=models.BooleanField(default=False, verbose_name='Declined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_identity_verified',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
