# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171128_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='docs_received',
        ),
    ]
