# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_remove_account_docs_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleJnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jnt_value', models.FloatField()),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presale_jnt',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='is_presale_account',
            field=models.BooleanField(default=False),
        ),
    ]
