# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171130_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_document_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
