# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_account_is_document_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rendered_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
