# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_notification_rendered_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
