# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_affiliate'),
        ('api', '0023_account_verification_started_at'),
    ]

    operations = [
    ]
