# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20171207_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
