# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import jco.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(upload_to=jco.api.models.unique_document_filename, verbose_name='uploaded document'),
        ),
    ]
