# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
