# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171212_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default='not_confirmed', max_length=20),
        ),
    ]
