# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20171212_2038'),
        ('api', '0027_auto_20171209_2108'),
    ]

    operations = [
    ]
