# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20171214_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='address',
        ),
    ]
