# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_withdraw_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='mined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
