# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20171214_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
