# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20171214_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalejnt',
            name='comment',
            field=models.CharField(default='ANGEL ROUND / PRESALE', max_length=32),
        ),
        migrations.AddField(
            model_name='presalejnt',
            name='is_sale_allocation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
