# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0032_auto_20171214_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJntPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_jnt_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_jnt_price',
            },
        ),
    ]
