# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20171218_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalejnt',
            name='is_presale_round',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
