# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_userjntprice'),
        ('api', '0034_presalejnt_is_presale_round'),
    ]

    operations = [
    ]
