# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20171222_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_sale_allocation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jnt',
            name='is_sale_allocation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jnt',
            name='jnt_to_usd_rate',
            field=models.FloatField(help_text='If you change this value and save - jnt_value will be recalculated as jnt_value = usd_value / jnt_to_usd_rate'),
        ),
    ]
