# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_jnt_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalejnt',
            name='currency_to_usd_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presalejnt',
            name='usd_value',
            field=models.FloatField(default=0),
        ),
    ]
