# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20171226_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='last_notification_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
