"""empty message

Revision ID: ad716bfa20de
Revises: dad9342e0c85
Create Date: 2017-10-19 23:17:33.450051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad716bfa20de'
down_revision = 'dad9342e0c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('citizenship', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('docs_received', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###
